{
  "hash": "9a33fbdf1159c04fd1668de7703799ed",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Supervised learning: linear regression\"\nauthor: \"<br>SURE 2025<br><br>Department of Statistics & Data Science<br>Carnegie Mellon University\"\nfooter:  \"[36-SURE.github.io/2025](https://36-sure.github.io/2025)\"\nformat:\n  revealjs:\n    theme: theme.scss\n    chalkboard: true\n    smaller: true\n    slide-number: c/t\n    code-line-numbers: false\n    linestretch: 1.25\n    html-math-method:\n      method: mathjax\n      url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n\n\n\n\n\n# Background\n\n## Supervised learning\n\n* General setup: Given a dataset of $n$ observations (rows) and $p$ variables (columns)\n\n. . .\n\n* Response/outcome/target/dependent variable $Y$ in one of the $p$ variables\n\n. . .\n\n* **Goal**: uncover associations between a set of predictors/features/covariates/explanatory variables and a response variable\n\n  * Accurately predict unseen test cases\n\n  * Understand which features affect the response (and how)\n\n  * Assess the quality of our predictions and inferences\n  \n. . .  \n\n* Two main types of problems\n\n  * Regression: estimate average value of response (i.e. the response is quantitative)\n\n  * Classification: determine the most likely class of a set of discrete response variable classes (i.e. the response is categorical)\n  \n## Examples of supervised learning methods\n\n* Linear regression (today)\n\n* Generalized linear models (GLMs) and penalized versions (lasso, ridge, elastic net)\n\n* Smoothing splines, generalized additive models (GAMs)\n\n* Decision trees and its variants (e.g., random forests, boosting)\n\n* Deep learning, neural networks\n\n## Resources\n\n*   [Advanced Data Analysis from an Elementary Point of View](https://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/ADAfaEPoV.pdf) (aka the greatest book that will never be published)\n\n*   [The Truth about Linear Regression](https://www.stat.cmu.edu/~cshalizi/TALR/TALR.pdf)\n\n> \"Regression\", in statistical jargon, is the problem of guessing the average level of some quantitative response variable from various predictor variables. - [Note GOAT](http://bactra.org/notebooks/regression.html)\n\n## Simple linear regression\n\n**Linear regression is used when the response variable is quantitative**\n\n. . .\n\nAssume a __linear relationship__ for $Y = f(X)$ $$Y_{i}=\\beta_{0}+\\beta_{1} X_{i}+\\epsilon_{i}, \\quad \\text { for } i=1,2, \\dots, n$$\n\n- $Y_i$ is the $i$th value for the __response__ variable\n  \n- $X_i$ is the $i$th value for the __predictor__ variable\n\n. . .\n  \n- $\\beta_0$ is an _unknown_, constant __intercept__\n\n  -   average value for $Y$ if $X = 0$ (be careful sometimes...)\n  \n- $\\beta_1$ is an _unknown_, constant __slope__\n\n  -   change in average value for $Y$ for each one-unit increase in $X$\n  \n. . .\n  \n- $\\epsilon_i$ is the __random__ noise\n\n    -   assume __independent, identically distributed__ (_iid_) from a normal distribution \n\n    -   $\\epsilon_i \\overset{iid}{\\sim}N(0, \\sigma^2)$ with constant variance $\\sigma^2$\n\n\n\n## Simple linear regression estimation\n\nWe are estimating the __conditional expection (mean)__ for $Y$:\n\n$$\\mathbb{E}[Y_i \\mid X_i] = \\beta_0 + \\beta_1X_i$$\n\n- average value for $Y$ given the value for $X$\n\n. . .\n\nHow do we estimate the __best fitted__ line?\n\n. . .\n\n__Ordinary least squares (OLS)__ - by minimizing the __residual sum of squares (RSS)__\n\n$$\\text{RSS} \\left(\\beta_{0}, \\beta_{1}\\right)=\\sum_{i=1}^{n}\\left[Y_{i}-\\left(\\beta_{0}+\\beta_{1} X_{i}\\right)\\right]^{2}=\\sum_{i=1}^{n}\\left(Y_{i}-\\beta_{0}-\\beta_{1} X_{i}\\right)^{2}$$\n\n. . .\n\n$$\\widehat{\\beta}_{1}=\\frac{\\sum_{i=1}^{n}\\left(X_{i}-\\bar{X}\\right)\\left(Y_{i}-\\bar{Y}\\right)}{\\sum_{i=1}^{n}\\left(X_{i}-\\bar{X}\\right)^{2}} \\quad \\text{ and } \\quad \\widehat{\\beta}_{0}=\\bar{Y}-\\widehat{\\beta}_{1} \\bar{X}$$\n\nwhere $\\displaystyle \\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i$ and $\\displaystyle \\bar{Y} = \\frac{1}{n}\\sum_{i=1}^n Y_i$\n\n## Visual explanation\n\n* Imagine a 2D scatterplot with different data points\n\n* Linear regression aims to find a \"best fit\" line that minimizes the vertical distance between the line and the data points\n\n  * The vertical distance is known as a residual (difference between the actual y-value of a data point and the predicted y-value on the regression line)\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n:::\n:::\n\n# Linear regression in `R`\n\n## Data: Capital Bikeshare Ridership\n\nDaily count of rental bikes between years 2011 and 2012 in Capital bikeshare system with the corresponding weather and seasonal information.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ntheme_set(theme_light())\n\nbikes <- read_csv(\"https://raw.githubusercontent.com/36-SURE/2025/refs/heads/main/data/bikes.csv\")\nglimpse(bikes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 500\nColumns: 13\n$ date        <date> 2011-01-01, 2011-01-03, 2011-01-04, 2011-01-05, 2011-01-0…\n$ season      <chr> \"winter\", \"winter\", \"winter\", \"winter\", \"winter\", \"winter\"…\n$ year        <dbl> 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011…\n$ month       <chr> \"Jan\", \"Jan\", \"Jan\", \"Jan\", \"Jan\", \"Jan\", \"Jan\", \"Jan\", \"J…\n$ day_of_week <chr> \"Sat\", \"Mon\", \"Tue\", \"Wed\", \"Fri\", \"Sat\", \"Mon\", \"Tue\", \"W…\n$ weekend     <lgl> TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALS…\n$ holiday     <chr> \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\"…\n$ temp_actual <dbl> 57.39952, 46.49166, 46.76000, 48.74943, 46.50332, 44.17700…\n$ temp_feel   <dbl> 64.72625, 49.04645, 51.09098, 52.63430, 50.79551, 46.60286…\n$ humidity    <dbl> 80.5833, 43.7273, 59.0435, 43.6957, 49.8696, 53.5833, 48.2…\n$ windspeed   <dbl> 10.749882, 16.636703, 10.739832, 12.522300, 11.304642, 17.…\n$ weather_cat <chr> \"categ2\", \"categ1\", \"categ1\", \"categ1\", \"categ2\", \"categ2\"…\n$ rides       <dbl> 654, 1229, 1454, 1518, 1362, 891, 1280, 1220, 1137, 1368, …\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n## Modeling bike ridership\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n* To best serve its members, Capital Bikeshare must understand the demand for its service\n\n* Modeling & predicting bikeshare `rides`\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbikes |>\n  ggplot(aes(x = rides)) +\n  geom_histogram(color = \"black\", fill = \"gray\")\n```\n:::\n\n\n\n\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n:::\n:::\n\n## Relationship between rides and feels-like temperature\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrides_temp <- bikes |>\n  ggplot(aes(x = temp_feel, y = rides)) +\n  geom_point(size = 3, alpha = 0.5)\nrides_temp\n```\n:::\n\n\n\n\nWe fit linear regression models using `lm()`, formula is input as: `response ~ predictor`\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimple_lm <- lm(rides ~ temp_feel, data = bikes) \n```\n:::\n\n\n\n\n:::\n\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n:::\n:::\n\n## Model summary using  `summary()`\n\n::: columns\n::: {.column width=\"45%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(simple_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rides ~ temp_feel, data = bikes)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3658.9 -1029.7  -149.7   950.6  3437.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2179.27     358.63  -6.077 2.44e-09 ***\ntemp_feel      81.88       5.12  15.992  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1281 on 498 degrees of freedom\nMultiple R-squared:  0.3393,\tAdjusted R-squared:  0.338 \nF-statistic: 255.7 on 1 and 498 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"55%\" style=\"text-align: left;\"}\n\nHow do we read the summary output?\n\nModel: $\\ \\small \\text{Rides} = \\beta_0 + \\beta_1 \\ \\text{Temperature} + \\epsilon$\n\nFrom output: $\\ \\small \\hat{\\beta}_0 = -2179.27$ and $\\small \\hat{\\beta}_1 = 81.88$\n\nOLS line: $\\ \\ \\small \\widehat{\\text{Rides}} = -2179.27 + 81.88 \\ \\text{Temperature}$\n\nInterpretation of $\\hat \\beta_1$: estimated change in y for a one unit change in x\n\nIn context: For every additional $^{\\circ}$ F in feels-like temperature, the expected ridership increases by about 82 rides.\n\n:::\n:::\n\n## Inference: hypothesis testing\n\n::: columns\n::: {.column width=\"45%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(simple_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rides ~ temp_feel, data = bikes)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3658.9 -1029.7  -149.7   950.6  3437.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2179.27     358.63  -6.077 2.44e-09 ***\ntemp_feel      81.88       5.12  15.992  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1281 on 498 degrees of freedom\nMultiple R-squared:  0.3393,\tAdjusted R-squared:  0.338 \nF-statistic: 255.7 on 1 and 498 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"55%\" style=\"text-align: left;\"}\n\nEstimates of uncertainty for model coefficients via __standard errors__ $$\\quad \\widehat{SE}(\\hat{\\beta}_0) = 358.63 \\quad \\text{and} \\quad \\widehat{SE}(\\hat{\\beta}_1) = 5.12$$\n\nWe're testing whether there is a linear relationship between the predictor and the response $$\\quad H_0: \\beta_1 = 0 \\quad \\text{vs} \\quad H_1: \\beta_1 \\neq 0$$\n\nTest statistic: $$t = \\frac{\\hat{\\beta}_1}{\\widehat{SE}(\\hat{\\beta}_1)} = \\frac{81.88}{5.12} = 15.99$$\n\n:::\n:::\n\n## Inference: hypothesis testing\n\n::: columns\n::: {.column width=\"45%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(simple_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rides ~ temp_feel, data = bikes)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3658.9 -1029.7  -149.7   950.6  3437.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2179.27     358.63  -6.077 2.44e-09 ***\ntemp_feel      81.88       5.12  15.992  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1281 on 498 degrees of freedom\nMultiple R-squared:  0.3393,\tAdjusted R-squared:  0.338 \nF-statistic: 255.7 on 1 and 498 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"55%\" style=\"text-align: left;\"}\n\nRecall that we're testing $$\\quad H_0: \\beta_1 = 0 \\quad \\text{vs} \\quad H_1: \\beta_1 \\neq 0$$\n\n* $p$-value (i.e., `Pr(>|t|)`): probability of observing a value as extreme as the observed test statistic (under the null hypothesis)\n  \n* $p$-value $< \\alpha = 0.05$ (conventional threshold): __sufficient evidence to reject the null hypothesis that the coefficient is zero__\n\n* In context: There is a statistically significant association between temperature and number of bikeshare rides, $\\small \\hat \\beta_1 = 81.88, t = 15.99,p$-value $<0.001$.\n\n:::\n:::\n  \n## Model summary using the [`broom`](https://cran.r-project.org/web/packages/broom/vignettes/broom.html) package\n\nThe 3 `broom` functions (Note: the output is always a tibble)\n\n*   `tidy()`: coefficients table in a tidy format\n\n*   `glance()`: produces summary metrics of a model fit\n\n*   `augment()`: adds/\"augments\" columns to the original data (e.g., adding predictions)\n\n. . .\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(broom)\ntidy(simple_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  -2179.     359.       -6.08 2.44e- 9\n2 temp_feel       81.9      5.12     16.0  9.29e-47\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(simple_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.339         0.338 1281.      256. 9.29e-47     1 -4286. 8579. 8591.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\n\n\n## Confidence interval for model coefficients\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(simple_lm, conf.int = TRUE, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)  -2179.     359.       -6.08 2.44e- 9  -2884.    -1475. \n2 temp_feel       81.9      5.12     16.0  9.29e-47     71.8      91.9\n```\n\n\n:::\n:::\n\n\n\n\nIn-context interpretation (for `temp_feel`)\n\n* For every additional $^{\\circ}$ F in feels-like temperature, the expected ridership increases by about 82 rides (95% CI [71.8, 91.9])\n\n. . . \n\n* We're 95% confident that every additional degree Fahrenheit in temperature is associated with an increase of about 72 to 92 rides in expected ridership.\n\n\n## Coefficient of determination\n\n* In linear regression, the square of the correlation coefficient happens to be exactly the coefficient of\ndetermination\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor(bikes$temp_feel, bikes$rides)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5824898\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(bikes$temp_feel, bikes$rides) ^ 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3392944\n```\n\n\n:::\n:::\n\n\n\n\n* $R^2$ estimates the __proportion of the variance__ of $Y$ explained by $X$ \n\n* More generally: variance of model predictions / variance of $Y$\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvar(predict(simple_lm)) / var(bikes$rides) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3392944\n```\n\n\n:::\n:::\n\n\n\n\n* Interpretation: 33.9% of the variability in the number of bikeshare rides can be explained by the linear relationship between\nridership and feels-like temperature (the remaining 66.1% of the variation is due to other factors and/or noise)\n\n## Generating predictions\n\nWe can use the `predict()` or `fitted()` function to get the fitted values from the regression model\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(predict(simple_lm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1        2        3        4        5        6 \n3120.513 1836.652 2004.058 2130.425 1979.865 1636.571 \n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(fitted(simple_lm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1        2        3        4        5        6 \n3120.513 1836.652 2004.058 2130.425 1979.865 1636.571 \n```\n\n\n:::\n:::\n\n\n\n\n## Plot observed values against predictions\n\nUseful diagnostic (for __any type of model__, not just linear regression!) \n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbikes |>\n  mutate(pred = predict(simple_lm)) |> \n  ggplot(aes(x = pred, y = rides)) +\n  geom_point(alpha = 0.5, size = 3) +\n  geom_abline(slope = 1, intercept = 0, \n              linetype = \"dashed\",\n              color = \"red\",\n              linewidth = 2)\n```\n:::\n\n\n\n\n- \"Perfect\" model will follow __diagonal__\n\n:::\n\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\n:::\n:::\n\n\n\n## Plot observed values against predictions\n\nAugment the data with model output using the [`broom` package](https://cran.r-project.org/web/packages/broom/vignettes/broom.html)\n\n`augment()` adds various columns from model fit we can use in plotting for model diagnostics\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbikes <- simple_lm |> \n  augment(bikes) \nbikes |>\n  ggplot(aes(x = .fitted, y = rides)) + \n  geom_point(alpha = 0.5, size = 3) +\n  geom_abline(slope = 1, intercept = 0, color = \"red\", \n              linetype = \"dashed\", linewidth = 2)\n```\n:::\n\n\n\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\n:::\n:::\n\n## Assessing assumptions of linear regression\n\nSimple linear regression assumes $Y_i \\overset{iid}{\\sim} N(\\beta_0 + \\beta_1 X_i, \\sigma^2)$\n\n- If this is true, then $Y_i - \\hat{Y}_i \\overset{iid}{\\sim} N(0, \\sigma^2)$\n\n. . .\n\nPlot residuals against $\\hat{Y}_i$, __residuals vs fit__ plot\n\n- Used to assess linearity, any divergence from mean 0\n\n- Used to assess equal variance, i.e., if $\\sigma^2$ is homogenous across predictions/fits $\\hat{Y}_i$\n\n. . .\n\nMore difficult to assess the independence and fixed $X$ assumptions\n\n- Make these assumptions based on subject-matter knowledge\n\n\n\n## Plot residuals against predicted values\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n- Residuals = observed - predicted\n\n- Interpretation of residuals in context?\n\n- Conditional on the predicted values, the __residuals should have a mean of zero__\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbikes |>\n  ggplot(aes(x = .fitted, y = .resid)) + \n  geom_point(alpha = 0.5, size = 3) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", \n             color = \"red\", linewidth = 2) +\n  # plot the residual mean\n  geom_smooth(se = FALSE)\n```\n:::\n\n\n\n\n- Residuals __should NOT display any pattern__\n\n- Two things to look for:\n\n  -   Any trend around horizontal reference line?\n\n  -   Equal vertical spread?\n\n:::\n\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\n:::\n:::\n\n## Linear regression with one categorical predictor\n\n* Model `rides` by the `season` (4 levels: `spring`, `summer`, `fall`, `winter`)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# table(bikes$season)\n```\n:::\n\n\n\n\n* We are changing the intercept of our regression line by including a categorical variable\n\n* Notice we only get 3 coefficients for the season besides the intercept $$\\widehat{\\text{Rides}} = 4051 - 265 \\ I_{\\texttt{spring}} + 543 \\ I_{\\texttt{summer}} - 1686 \\ I_{\\texttt{winter}}$$\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nseason_lm <- lm(rides ~ season, data = bikes)\ntidy(season_lm, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term         estimate std.error statistic   p.value conf.low conf.high\n  <chr>           <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)     4051.      107.     38.0  7.15e-149   3841.     4260. \n2 seasonspring    -265.      158.     -1.68 9.35e-  2   -574.       44.8\n3 seasonsummer     543.      246.      2.21 2.76e-  2     60.2    1027. \n4 seasonwinter   -1686.      152.    -11.1  1.11e- 25  -1985.    -1388. \n```\n\n\n:::\n:::\n\n\n\n\n## Linear regression with one categorical predictor\n\n$$\\widehat{\\text{Rides}} = 4050.7 - 264.7 \\ I_{\\texttt{spring}} + 543.5 \\ I_{\\texttt{summer}} - 1686.3 \\ I_{\\texttt{winter}}$$\n\n* By default, `R` turns the categorical variables of $m$ levels (e.g. 4 seasons in this dataset) into $m-1$ indicator/dummy variables for different categories relative to a baseline/reference level\n\n  * Indicator/dummy variables: binary variables (1: that level, 0: not that level) \n\n  * `R` uses alphabetical order to determine the reference level (`fall` season in this case)\n  \n## Linear regression with one categorical predictor\n\n$$\\widehat{\\text{Rides}} = 4050.7 - 264.7 \\ I_{\\texttt{spring}} + 543.5 \\ I_{\\texttt{summer}} - 1686.3 \\ I_{\\texttt{winter}}$$\n\n* The intercept term gives us the (baseline) average y for the reference level\n  \n  * In context, the expected daily bikeshare rides during fall season is 4051 rides (95% CI [3841, 4260])\n\n* The values for the coefficient estimates indicate the expected change in the response variable relative to the reference level\n\n  * For example, the expected bikeshare rides during winter is 1686 rides lower (95% CI [-1985, -1388]) than during fall (does this make sense?)\n  \n## Comparing observed values and predictions\n\n* Similar to before, we can plot the actual and predicted ridership\n\n* To reiterate, all we're doing is changing the intercept of our regression line by including a categorical variable\n\n::: columns\n::: {.column width=\"30%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbikes |>\n  mutate(season_pred = predict(season_lm)) |> \n  ggplot(aes(x = rides, y = season_pred)) +\n  geom_point(size = 3, alpha = 0.5) +\n  facet_wrap(~ season, ncol = 4) +\n  labs(x = \"Actual number of rides\", \n       y = \"Predicted number of rides\")\n```\n:::\n\n\n\n\n:::\n\n\n::: {.column width=\"70%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n:::\n\n:::\n\n## Interactions\n\n* An interaction allows one predictor’s association with the outcome to depend on values of another predictor\n\n. . .\n\n* Example: interaction between a categorical variable (`season`) and a quantitative variable (`temp_feel`)\n\n  * When to include interaction? When we believe relationships between a quantitative variable and the response differ across categories (of a categorical variable)\n\n  * 4 different lines for each `season` in modeling relationship between `rides` and `temp_feel`\n\n  * This means those regression lines have different intercepts as well as different slopes\n  \n. . .  \n  \n* For more on interactions, see these [notes](https://www.medicine.mcgill.ca/epidemiology/joseph/courses/EPIB-621/interaction.pdf)\n  \n## Visualizing interactions\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbikes |> \n  ggplot(aes(x = temp_feel, y = rides, color = season)) +\n  geom_point(size = 2, alpha = 0.6) +\n  geom_smooth(method = \"lm\", se = FALSE, linewidth = 2) +\n  ggthemes::scale_color_colorblind()\n```\n\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n## Interpreting interactions\n\n$$\n\\begin{aligned}\n{\\text{Rides}} &= \\beta_0 + \\beta_1 \\ \\text{Temp} + \\beta_2 \\ I_{\\texttt{spring}} + \\beta_3 \\ I_{\\texttt{summer}} + \\beta_4 \\ I_{\\texttt{winter}} \\\\\n&+ \\beta_5 \\{ \\text{Temp } \\times I_{\\texttt{spring}} \\} +  \\beta_6 \\{ \\text{Temp } \\times I_{\\texttt{summer}} \\} +  \\beta_7 \\{ \\text{Temp } \\times I_{\\texttt{winter}} \\} + \\epsilon \\\\\n\\end{aligned}\n$$\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninteraction_lm <- lm(rides ~ temp_feel * season, \n                     data = bikes)\ntidy(interaction_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{style='font-size: 0.55em;'}\n# A tibble: 8 × 5\n  term                   estimate std.error statistic     p.value\n  <chr>                     <dbl>     <dbl>     <dbl>       <dbl>\n1 (Intercept)               238.      773.      0.308 0.758      \n2 temp_feel                  54.9      11.0     4.97  0.000000935\n3 seasonspring            -3244.     1222.     -2.65  0.00819    \n4 seasonsummer             3393.     2921.      1.16  0.246      \n5 seasonwinter            -3020.     1032.     -2.93  0.00358    \n6 temp_feel:seasonspring     34.4      16.6     2.07  0.0386     \n7 temp_feel:seasonsummer    -43.2      35.9    -1.20  0.229      \n8 temp_feel:seasonwinter     31.6      15.8     1.99  0.0466     \n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n* $\\beta_0$ and $\\beta_1$ give the slope and intercept for the regression line (describing the relationship between ridership & temperature) for fall season (the reference level)\n\n* $\\beta_2$ measures the difference in the intercepts between spring and fall seasons \n\n* $\\beta_5$ shows how much the slopes change as we move from the regression line for fall (the reference level) to the line for spring\n\n* and so on...\n\n:::\n:::\n\n\n## Multiple linear regression \n\nWe can include as many variables as we want (assuming $n > p$)\n\n$$Y=\\beta_{0}+\\beta_{1} X_{1}+\\beta_{2} X_{2}+\\cdots+\\beta_{p} X_{p}+\\epsilon$$\n\nOLS estimates in matrix notation ($\\boldsymbol{X}$ is a $n \\times p$ matrix):\n  \n$$\\hat{\\boldsymbol{\\beta}} = (\\boldsymbol{X} ^T \\boldsymbol{X})^{-1}\\boldsymbol{X}^T\\boldsymbol{Y}$$\n\n. . .\n\nCan just add more variables to the formula in `R`\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmultiple_lm <- lm(rides ~ temp_feel + humidity, data = bikes)\n```\n:::\n\n\n\n\n- Use adjusted $R^2$  when including multiple variables $\\displaystyle 1 - \\frac{(1 - R^2)(n - 1)}{(n - p - 1)}$\n\n  - Adjusts for the number of variables in the model $p$  \n  \n  - Adding more variables __will always increase__ the model's (unadjusted) $R^2$\n  \nREAD THIS: [$R^2$ myths](https://www.stat.cmu.edu/~cshalizi/TALR/TALR.pdf#page=181) \n\n[Get your $R^2$ out of here](https://www.tiktok.com/@fatgreggy/video/7186499956058950958)\n\n\n## What about the normality assumption?\n\n* Model: $Y=\\beta_{0}+\\beta_{1} X_{1}+\\beta_{2} X_{2}+\\cdots+\\beta_{p} X_{p}+\\epsilon$\n\n- $\\epsilon_i$ is the __random__ noise: assume __independent and identically distributed__ (_iid_) from a Normal distribution $\\epsilon_i \\overset{iid}{\\sim}N(0, \\sigma^2)$ with constant variance $\\sigma^2$\n\n. . .\n\n* __OLS doesn't care about this assumption__, it's just estimating coefficients!\n\n. . .\n\n* In order to perform inference, __we need to impose additional assumptions__\n\n* By assuming $\\epsilon_i \\overset{iid}{\\sim}N(0, \\sigma^2)$, what we really mean is $Y \\overset{iid}{\\sim}N(\\beta_{0}+\\beta_{1} X_{1}+\\beta_{2} X_{2}+\\cdots+\\beta_{p} X_{p}, \\sigma^2)$\n\n. . .\n\n* So we're estimating the mean $\\mu$ of this conditional distribution, but what about $\\sigma^2$?\n  \n. . .\n\n* [Unbiased estimate](https://bradleyboehmke.github.io/HOML/linear-regression.html#simple-linear-regression) $\\displaystyle \\hat{\\sigma}^2 = \\frac{\\text{RSS}}{n - (p + 1)}$\n\n* __Degrees of freedom__:  $n - (p + 1)$, data supplies us with $n$ \"degrees of freedom\" and we used up $p + 1$\n\n\n## Regression confidence intervals vs prediction intervals\n\nDo we want to predict the mean response for a particular value $x^*$ of the explanatory variable or do we want to predict the response for an individual case?\n\nExample: \n\n*   if we would like to know the average ridership for **all** days with feels-like temperature of 70 degrees Fahrenheit, then we would use an interval for the **mean response**\n\n*   if we want an interval to contain the ridership of **a particular** day with feels-like temperature of 70 degrees Fahrenheit, then we need the interval for **a single prediction**\n\n\n## Regression confidence intervals\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n- `geom_smooth()` displays __confidence intervals__ for the regression line\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# predict(simple_lm, interval = \"confidence\")\nlm_plot <- bikes |>\n  ggplot(aes(x = temp_feel, y = rides)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\")\nlm_plot\n```\n:::\n\n\n\n\n:::\n\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-23-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\n:::\n:::\n\n\n---\n\n## Regression confidence intervals\n\n*   Interval estimate for the MEAN response at a given observation (i.e. for the predicted AVERAGE $\\hat{\\beta}_0 + \\hat{\\beta}_1 x^*$)\n\n*   Based on standard errors for the estimated regression line at $x^*$ $$SE_{\\text{line}}\\left(x^{*}\\right)=\\hat{\\sigma} \\cdot \\sqrt{\\frac{1}{n}+\\frac{\\left(x^{*}-\\bar{x}\\right)^{2}}{\\sum_{i=1}^{n}\\left(x_{i}-\\bar{x}\\right)^{2}}}$$\n\n*   Variation only comes from uncertainty in the parameter \n\n## Regression prediction intervals\n\n*   interval estimate for an INDIVIDUAL response at a given (new) observation \n\n*   add the variance $\\sigma^2$ of a __single predicted value__ $$SE_{\\text{pred}}\\left(x^{*}\\right)=\\hat{\\sigma} \\cdot \\sqrt{1 + \\frac{1}{n}+\\frac{\\left(x^{*}-\\bar{x}\\right)^{2}}{\\sum_{i=1}^{n}\\left(x_{i}-\\bar{x}\\right)^{2}}}$$\n\n*   Variation comes from uncertainty in parameter estimates and error variance \n\n## Confidence intervals versus prediction intervals\n\nGenerate 95% intervals\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# predict(simple_lm, interval = \"prediction\")\nlm_plot +\n  geom_ribbon(\n    data = augment(simple_lm, interval = \"prediction\"),\n    aes(ymin = .lower, ymax = .upper),\n    color = \"red\", fill = NA\n  )\n```\n:::\n\n\n\n\n*   The standard error for predicting an individual response will always be larger than for predicting a mean response\n\n*   Prediction intervals will always be wider than confidence intervals\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-linear_files/figure-revealjs/unnamed-chunk-24-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\n:::\n:::\n",
    "supporting": [
      "11-linear_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}