<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <meta name="author" content=" SURE 2025 Department of Statistics &amp; Data Science Carnegie Mellon University">
  <title>SURE 2025 – Supervised learning: linear regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-97331e35b7c4b061e26f0e6fc4589e47.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Supervised learning: linear regression</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
<br>SURE 2025<br><br>Department of Statistics &amp; Data Science<br>Carnegie Mellon University 
</div>
</div>
</div>

</section>
<section>
<section id="background" class="title-slide slide level1 center">
<h1>Background</h1>

</section>
<section id="supervised-learning" class="slide level2">
<h2>Supervised learning</h2>
<ul>
<li>General setup: Given a dataset of <span class="math inline">\(n\)</span> observations (rows) and <span class="math inline">\(p\)</span> variables (columns)</li>
</ul>
<div class="fragment">
<ul>
<li>Response/outcome/target/dependent variable <span class="math inline">\(Y\)</span> in one of the <span class="math inline">\(p\)</span> variables</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p><strong>Goal</strong>: uncover associations between a set of predictors/features/covariates/explanatory variables and a response variable</p>
<ul>
<li><p>Accurately predict unseen test cases</p></li>
<li><p>Understand which features affect the response (and how)</p></li>
<li><p>Assess the quality of our predictions and inferences</p></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>Two main types of problems</p>
<ul>
<li><p>Regression: estimate average value of response (i.e.&nbsp;the response is quantitative)</p></li>
<li><p>Classification: determine the most likely class of a set of discrete response variable classes (i.e.&nbsp;the response is categorical)</p></li>
</ul></li>
</ul>
</div>
</section>
<section id="examples-of-supervised-learning-methods" class="slide level2">
<h2>Examples of supervised learning methods</h2>
<ul>
<li><p>Linear regression (today)</p></li>
<li><p>Generalized linear models (GLMs) and penalized versions (lasso, ridge, elastic net)</p></li>
<li><p>Smoothing splines, generalized additive models (GAMs)</p></li>
<li><p>Decision trees and its variants (e.g., random forests, boosting)</p></li>
<li><p>Deep learning, neural networks</p></li>
</ul>
</section>
<section id="resources" class="slide level2">
<h2>Resources</h2>
<ul>
<li><p><a href="https://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/ADAfaEPoV.pdf">Advanced Data Analysis from an Elementary Point of View</a> (aka the greatest book that will never be published)</p></li>
<li><p><a href="https://www.stat.cmu.edu/~cshalizi/TALR/TALR.pdf">The Truth about Linear Regression</a></p></li>
</ul>
<blockquote>
<p>“Regression”, in statistical jargon, is the problem of guessing the average level of some quantitative response variable from various predictor variables. - <a href="http://bactra.org/notebooks/regression.html">Note GOAT</a></p>
</blockquote>
</section>
<section id="simple-linear-regression" class="slide level2">
<h2>Simple linear regression</h2>
<p><strong>Linear regression is used when the response variable is quantitative</strong></p>
<div class="fragment">
<p>Assume a <strong>linear relationship</strong> for <span class="math inline">\(Y = f(X)\)</span> <span class="math display">\[Y_{i}=\beta_{0}+\beta_{1} X_{i}+\epsilon_{i}, \quad \text { for } i=1,2, \dots, n\]</span></p>
<ul>
<li><p><span class="math inline">\(Y_i\)</span> is the <span class="math inline">\(i\)</span>th value for the <strong>response</strong> variable</p></li>
<li><p><span class="math inline">\(X_i\)</span> is the <span class="math inline">\(i\)</span>th value for the <strong>predictor</strong> variable</p></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p><span class="math inline">\(\beta_0\)</span> is an <em>unknown</em>, constant <strong>intercept</strong></p>
<ul>
<li>average value for <span class="math inline">\(Y\)</span> if <span class="math inline">\(X = 0\)</span> (be careful sometimes…)</li>
</ul></li>
<li><p><span class="math inline">\(\beta_1\)</span> is an <em>unknown</em>, constant <strong>slope</strong></p>
<ul>
<li>change in average value for <span class="math inline">\(Y\)</span> for each one-unit increase in <span class="math inline">\(X\)</span></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p><span class="math inline">\(\epsilon_i\)</span> is the <strong>random</strong> noise</p>
<ul>
<li><p>assume <strong>independent, identically distributed</strong> (<em>iid</em>) from a normal distribution</p></li>
<li><p><span class="math inline">\(\epsilon_i \overset{iid}{\sim}N(0, \sigma^2)\)</span> with constant variance <span class="math inline">\(\sigma^2\)</span></p></li>
</ul></li>
</ul>
</div>
</section>
<section id="simple-linear-regression-estimation" class="slide level2">
<h2>Simple linear regression estimation</h2>
<p>We are estimating the <strong>conditional expection (mean)</strong> for <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[\mathbb{E}[Y_i \mid X_i] = \beta_0 + \beta_1X_i\]</span></p>
<ul>
<li>average value for <span class="math inline">\(Y\)</span> given the value for <span class="math inline">\(X\)</span></li>
</ul>
<div class="fragment">
<p>How do we estimate the <strong>best fitted</strong> line?</p>
</div>
<div class="fragment">
<p><strong>Ordinary least squares (OLS)</strong> - by minimizing the <strong>residual sum of squares (RSS)</strong></p>
<p><span class="math display">\[\text{RSS} \left(\beta_{0}, \beta_{1}\right)=\sum_{i=1}^{n}\left[Y_{i}-\left(\beta_{0}+\beta_{1} X_{i}\right)\right]^{2}=\sum_{i=1}^{n}\left(Y_{i}-\beta_{0}-\beta_{1} X_{i}\right)^{2}\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[\widehat{\beta}_{1}=\frac{\sum_{i=1}^{n}\left(X_{i}-\bar{X}\right)\left(Y_{i}-\bar{Y}\right)}{\sum_{i=1}^{n}\left(X_{i}-\bar{X}\right)^{2}} \quad \text{ and } \quad \widehat{\beta}_{0}=\bar{Y}-\widehat{\beta}_{1} \bar{X}\]</span></p>
<p>where <span class="math inline">\(\displaystyle \bar{X} = \frac{1}{n}\sum_{i=1}^n X_i\)</span> and <span class="math inline">\(\displaystyle \bar{Y} = \frac{1}{n}\sum_{i=1}^n Y_i\)</span></p>
</div>
</section>
<section id="visual-explanation" class="slide level2">
<h2>Visual explanation</h2>
<ul>
<li><p>Imagine a 2D scatterplot with different data points</p></li>
<li><p>Linear regression aims to find a “best fit” line that minimizes the vertical distance between the line and the data points</p>
<ul>
<li>The vertical distance is known as a residual (difference between the actual y-value of a data point and the predicted y-value on the regression line)</li>
</ul></li>
</ul>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section></section>
<section>
<section id="linear-regression-in-r" class="title-slide slide level1 center">
<h1>Linear regression in <code>R</code></h1>

</section>
<section id="data-capital-bikeshare-ridership" class="slide level2">
<h2>Data: Capital Bikeshare Ridership</h2>
<p>Daily count of rental bikes between years 2011 and 2012 in Capital bikeshare system with the corresponding weather and seasonal information.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_light</span>())</span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a>bikes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/36-SURE/2025/refs/heads/main/data/bikes.csv"</span>)</span>
<span id="cb1-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(bikes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 500
Columns: 13
$ date        &lt;date&gt; 2011-01-01, 2011-01-03, 2011-01-04, 2011-01-05, 2011-01-0…
$ season      &lt;chr&gt; "winter", "winter", "winter", "winter", "winter", "winter"…
$ year        &lt;dbl&gt; 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011…
$ month       &lt;chr&gt; "Jan", "Jan", "Jan", "Jan", "Jan", "Jan", "Jan", "Jan", "J…
$ day_of_week &lt;chr&gt; "Sat", "Mon", "Tue", "Wed", "Fri", "Sat", "Mon", "Tue", "W…
$ weekend     &lt;lgl&gt; TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALS…
$ holiday     &lt;chr&gt; "no", "no", "no", "no", "no", "no", "no", "no", "no", "no"…
$ temp_actual &lt;dbl&gt; 57.39952, 46.49166, 46.76000, 48.74943, 46.50332, 44.17700…
$ temp_feel   &lt;dbl&gt; 64.72625, 49.04645, 51.09098, 52.63430, 50.79551, 46.60286…
$ humidity    &lt;dbl&gt; 80.5833, 43.7273, 59.0435, 43.6957, 49.8696, 53.5833, 48.2…
$ windspeed   &lt;dbl&gt; 10.749882, 16.636703, 10.739832, 12.522300, 11.304642, 17.…
$ weather_cat &lt;chr&gt; "categ2", "categ1", "categ1", "categ1", "categ2", "categ2"…
$ rides       &lt;dbl&gt; 654, 1229, 1454, 1518, 1362, 891, 1280, 1220, 1137, 1368, …</code></pre>
</div>
</div>
</section>
<section id="modeling-bike-ridership" class="slide level2">
<h2>Modeling bike ridership</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<p>Interested in modeling bikeshare <code>rides</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>bikes <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> rides)) <span class="sc">+</span></span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"gray"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-5-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="relationship-between-rides-and-feels-like-temperature" class="slide level2">
<h2>Relationship between rides and feels-like temperature</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a>rides_temp <span class="ot">&lt;-</span> bikes <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> temp_feel, <span class="at">y =</span> rides)) <span class="sc">+</span></span>
<span id="cb4-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb4-4"><a aria-hidden="true" tabindex="-1"></a>rides_temp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We fit linear regression models using <code>lm()</code>, formula is input as: <code>response ~ predictor</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a>simple_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(rides <span class="sc">~</span> temp_feel, <span class="at">data =</span> bikes) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-6-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="model-summary-using-summary" class="slide level2">
<h2>Model summary using <code>summary()</code></h2>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simple_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rides ~ temp_feel, data = bikes)

Residuals:
    Min      1Q  Median      3Q     Max 
-3658.9 -1029.7  -149.7   950.6  3437.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2179.27     358.63  -6.077 2.44e-09 ***
temp_feel      81.88       5.12  15.992  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1281 on 498 degrees of freedom
Multiple R-squared:  0.3393,    Adjusted R-squared:  0.338 
F-statistic: 255.7 on 1 and 498 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div><div class="column" style="text-align: left;">
<p>How do we read the summary output?</p>
<p>Model: <span class="math inline">\(\ \small \text{Rides} = \beta_0 + \beta_1 \ \text{Temperature} + \epsilon\)</span></p>
<p>From output: <span class="math inline">\(\ \small \hat{\beta}_0 = -2179.27\)</span> and <span class="math inline">\(\small \hat{\beta}_1 = 81.88\)</span></p>
<p>OLS line: <span class="math inline">\(\ \ \small \widehat{\text{Rides}} = -2179.27 + 81.88 \ \text{Temperature}\)</span></p>
<p>Interpretation of <span class="math inline">\(\hat \beta_1\)</span>: estimated change in y for a one unit change in x</p>
<p>In context: For every additional <span class="math inline">\(^{\circ}\)</span> F in feels-like temperature, the expected ridership increases by about 82 rides.</p>
</div></div>
</section>
<section id="inference-hypothesis-testing" class="slide level2">
<h2>Inference: hypothesis testing</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simple_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rides ~ temp_feel, data = bikes)

Residuals:
    Min      1Q  Median      3Q     Max 
-3658.9 -1029.7  -149.7   950.6  3437.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2179.27     358.63  -6.077 2.44e-09 ***
temp_feel      81.88       5.12  15.992  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1281 on 498 degrees of freedom
Multiple R-squared:  0.3393,    Adjusted R-squared:  0.338 
F-statistic: 255.7 on 1 and 498 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div><div class="column" style="text-align: left;">
<p>Estimates of uncertainty for model coefficients via <strong>standard errors</strong> <span class="math display">\[\quad \widehat{SE}(\hat{\beta}_0) = 358.63 \quad \text{and} \quad \widehat{SE}(\hat{\beta}_1) = 5.12\]</span></p>
<p>We’re testing whether there is a linear relationship between the predictor and the response <span class="math display">\[\quad H_0: \beta_1 = 0 \quad \text{vs} \quad H_1: \beta_1 \neq 0\]</span></p>
<p>Test statistic: <span class="math display">\[t = \frac{\hat{\beta}_1}{\widehat{SE}(\hat{\beta}_1)} = \frac{81.88}{5.12} = 15.99\]</span></p>
</div></div>
</section>
<section id="inference-hypothesis-testing-1" class="slide level2">
<h2>Inference: hypothesis testing</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simple_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rides ~ temp_feel, data = bikes)

Residuals:
    Min      1Q  Median      3Q     Max 
-3658.9 -1029.7  -149.7   950.6  3437.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2179.27     358.63  -6.077 2.44e-09 ***
temp_feel      81.88       5.12  15.992  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1281 on 498 degrees of freedom
Multiple R-squared:  0.3393,    Adjusted R-squared:  0.338 
F-statistic: 255.7 on 1 and 498 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div><div class="column" style="text-align: left;">
<p>Recall that we’re testing <span class="math display">\[\quad H_0: \beta_1 = 0 \quad \text{vs} \quad H_1: \beta_1 \neq 0\]</span></p>
<ul>
<li><p><span class="math inline">\(p\)</span>-value (i.e., <code>Pr(&gt;|t|)</code>): probability of observing a value as extreme as the observed test statistic (under the null hypothesis)</p></li>
<li><p><span class="math inline">\(p\)</span>-value <span class="math inline">\(&lt; \alpha = 0.05\)</span> (conventional threshold): <strong>sufficient evidence to reject the null hypothesis that the coefficient is zero</strong></p></li>
<li><p>In context: There is a statistically significant association between temperature and number of bikeshare rides, <span class="math inline">\(\small \hat \beta_1 = 81.88, t = 15.99,p\)</span>-value <span class="math inline">\(&lt;0.001\)</span>.</p></li>
</ul>
</div></div>
</section>
<section id="model-summary-using-the-broom-package" class="slide level2">
<h2>Model summary using the <a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html"><code>broom</code></a> package</h2>
<p>The 3 <code>broom</code> functions (Note: the output is always a tibble)</p>
<ul>
<li><p><code>tidy()</code>: coefficients table in a tidy format</p></li>
<li><p><code>glance()</code>: produces summary metrics of a model fit</p></li>
<li><p><code>augment()</code>: adds/“augments” columns to the original data (e.g., adding predictions)</p></li>
</ul>
<div class="fragment">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb12-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(simple_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)  -2179.     359.       -6.08 2.44e- 9
2 temp_feel       81.9      5.12     16.0  9.29e-47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(simple_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.339         0.338 1281.      256. 9.29e-47     1 -4286. 8579. 8591.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
</div>
</section>
<section id="confidence-interval-for-model-coefficients" class="slide level2">
<h2>Confidence interval for model coefficients</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(simple_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  -2179.     359.       -6.08 2.44e- 9  -2884.    -1475. 
2 temp_feel       81.9      5.12     16.0  9.29e-47     71.8      91.9</code></pre>
</div>
</div>
<p>In-context interpretation (for <code>temp_feel</code>)</p>
<ul>
<li>For every additional <span class="math inline">\(^{\circ}\)</span> F in feels-like temperature, the expected ridership increases by about 82 rides (95% CI [71.8, 91.9])</li>
</ul>
<div class="fragment">
<ul>
<li>We’re 95% confident that every additional degree Fahrenheit in temperature is associated with an increase of about 72 to 92 rides in expected ridership.</li>
</ul>
</div>
</section>
<section id="coefficient-of-determination" class="slide level2">
<h2>Coefficient of determination</h2>
<ul>
<li>In linear regression, the square of the correlation coefficient happens to be exactly the coefficient of determination</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(bikes<span class="sc">$</span>temp_feel, bikes<span class="sc">$</span>rides)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5824898</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(bikes<span class="sc">$</span>temp_feel, bikes<span class="sc">$</span>rides) <span class="sc">^</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3392944</code></pre>
</div>
</div>
<ul>
<li><p><span class="math inline">\(R^2\)</span> estimates the <strong>proportion of the variance</strong> of <span class="math inline">\(Y\)</span> explained by <span class="math inline">\(X\)</span></p></li>
<li><p>More generally: variance of model predictions / variance of <span class="math inline">\(Y\)</span></p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(<span class="fu">predict</span>(simple_lm)) <span class="sc">/</span> <span class="fu">var</span>(bikes<span class="sc">$</span>rides) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3392944</code></pre>
</div>
</div>
<ul>
<li>Interpretation: 33.9% of the variability in the number of bikeshare rides can be explained by the linear relationship between ridership and feels-like temperature (the remaining 66.1% of the variation is due to other factors and/or noise)</li>
</ul>
</section>
<section id="generating-predictions" class="slide level2">
<h2>Generating predictions</h2>
<p>We can use the <code>predict()</code> or <code>fitted()</code> function to get the fitted values from the regression model</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(simple_lm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
3120.513 1836.652 2004.058 2130.425 1979.865 1636.571 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">fitted</span>(simple_lm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
3120.513 1836.652 2004.058 2130.425 1979.865 1636.571 </code></pre>
</div>
</div>
</section>
<section id="plot-observed-values-against-predictions" class="slide level2">
<h2>Plot observed values against predictions</h2>
<p>Useful diagnostic (for <strong>any type of model</strong>, not just linear regression!)</p>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a aria-hidden="true" tabindex="-1"></a>bikes <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(simple_lm)) <span class="sc">|&gt;</span> </span>
<span id="cb28-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> pred, <span class="at">y =</span> rides)) <span class="sc">+</span></span>
<span id="cb28-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, </span>
<span id="cb28-6"><a aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb28-7"><a aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb28-8"><a aria-hidden="true" tabindex="-1"></a>              <span class="at">linewidth =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>“Perfect” model will follow <strong>diagonal</strong></li>
</ul>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-13-1.png" class="quarto-figure quarto-figure-center" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="plot-observed-values-against-predictions-1" class="slide level2">
<h2>Plot observed values against predictions</h2>
<p>Augment the data with model output using the <a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html"><code>broom</code> package</a></p>
<p><code>augment()</code> adds various columns from model fit we can use in plotting for model diagnostics</p>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-hidden="true" tabindex="-1"></a>bikes <span class="ot">&lt;-</span> simple_lm <span class="sc">|&gt;</span> </span>
<span id="cb29-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(bikes) </span>
<span id="cb29-3"><a aria-hidden="true" tabindex="-1"></a>bikes <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> rides)) <span class="sc">+</span> </span>
<span id="cb29-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb29-7"><a aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-14-1.png" class="quarto-figure quarto-figure-center" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="assessing-assumptions-of-linear-regression" class="slide level2">
<h2>Assessing assumptions of linear regression</h2>
<p>Simple linear regression assumes <span class="math inline">\(Y_i \overset{iid}{\sim} N(\beta_0 + \beta_1 X_i, \sigma^2)\)</span></p>
<ul>
<li>If this is true, then <span class="math inline">\(Y_i - \hat{Y}_i \overset{iid}{\sim} N(0, \sigma^2)\)</span></li>
</ul>
<div class="fragment">
<p>Plot residuals against <span class="math inline">\(\hat{Y}_i\)</span>, <strong>residuals vs fit</strong> plot</p>
<ul>
<li><p>Used to assess linearity, any divergence from mean 0</p></li>
<li><p>Used to assess equal variance, i.e., if <span class="math inline">\(\sigma^2\)</span> is homogenous across predictions/fits <span class="math inline">\(\hat{Y}_i\)</span></p></li>
</ul>
</div>
<div class="fragment">
<p>More difficult to assess the independence and fixed <span class="math inline">\(X\)</span> assumptions</p>
<ul>
<li>Make these assumptions based on subject-matter knowledge</li>
</ul>
</div>
</section>
<section id="plot-residuals-against-predicted-values" class="slide level2">
<h2>Plot residuals against predicted values</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<ul>
<li><p>Residuals = observed - predicted</p></li>
<li><p>Interpretation of residuals in context?</p></li>
<li><p>Conditional on the predicted values, the <strong>residuals should have a mean of zero</strong></p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-hidden="true" tabindex="-1"></a>bikes <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span> </span>
<span id="cb30-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, </span>
<span id="cb30-5"><a aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot the residual mean</span></span>
<span id="cb30-7"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>Residuals <strong>should NOT display any pattern</strong></p></li>
<li><p>Two things to look for:</p>
<ul>
<li><p>Any trend around horizontal reference line?</p></li>
<li><p>Equal vertical spread?</p></li>
</ul></li>
</ul>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-15-1.png" class="quarto-figure quarto-figure-center" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="linear-regression-with-one-categorical-predictor" class="slide level2">
<h2>Linear regression with one categorical predictor</h2>
<ul>
<li>Model <code>rides</code> by the <code>season</code> (4 levels: <code>spring</code>, <code>summer</code>, <code>fall</code>, <code>winter</code>)</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># table(bikes$season)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>We are changing the intercept of our regression line by including a categorical variable</p></li>
<li><p>Notice we only get 3 coefficients for the season besides the intercept <span class="math display">\[\widehat{\text{Rides}} = 4051 - 265 \ I_{\texttt{spring}} + 543 \ I_{\texttt{summer}} - 1686 \ I_{\texttt{winter}}\]</span></p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a aria-hidden="true" tabindex="-1"></a>season_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(rides <span class="sc">~</span> season, <span class="at">data =</span> bikes)</span>
<span id="cb32-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(season_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  term         estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)     4051.      107.     38.0  7.15e-149   3841.     4260. 
2 seasonspring    -265.      158.     -1.68 9.35e-  2   -574.       44.8
3 seasonsummer     543.      246.      2.21 2.76e-  2     60.2    1027. 
4 seasonwinter   -1686.      152.    -11.1  1.11e- 25  -1985.    -1388. </code></pre>
</div>
</div>
</section>
<section id="linear-regression-with-one-categorical-predictor-1" class="slide level2">
<h2>Linear regression with one categorical predictor</h2>
<p><span class="math display">\[\widehat{\text{Rides}} = 4050.7 - 264.7 \ I_{\texttt{spring}} + 543.5 \ I_{\texttt{summer}} - 1686.3 \ I_{\texttt{winter}}\]</span></p>
<ul>
<li><p>By default, <code>R</code> turns the categorical variables of <span class="math inline">\(m\)</span> levels (e.g.&nbsp;4 seasons in this dataset) into <span class="math inline">\(m-1\)</span> indicator/dummy variables for different categories relative to a baseline/reference level</p>
<ul>
<li><p>Indicator/dummy variables: binary variables (1: that level, 0: not that level)</p></li>
<li><p><code>R</code> uses alphabetical order to determine the reference level (<code>fall</code> season in this case)</p></li>
</ul></li>
</ul>
</section>
<section id="linear-regression-with-one-categorical-predictor-2" class="slide level2">
<h2>Linear regression with one categorical predictor</h2>
<p><span class="math display">\[\widehat{\text{Rides}} = 4050.7 - 264.7 \ I_{\texttt{spring}} + 543.5 \ I_{\texttt{summer}} - 1686.3 \ I_{\texttt{winter}}\]</span></p>
<ul>
<li><p>The intercept term gives us the (baseline) average y for the reference level</p>
<ul>
<li>In context, the expected daily bikeshare rides during fall season is 4051 rides (95% CI [3841, 4260])</li>
</ul></li>
<li><p>The values for the coefficient estimates indicate the expected change in the response variable relative to the reference level</p>
<ul>
<li>For example, the expected bikeshare rides during winter is 1686 rides lower (95% CI [-1985, -1388]) than during fall (does this make sense?)</li>
</ul></li>
</ul>
</section>
<section id="comparing-observed-values-and-predictions" class="slide level2">
<h2>Comparing observed values and predictions</h2>
<ul>
<li><p>Similar to before, we can plot the actual and predicted ridership</p></li>
<li><p>To reiterate, all we’re doing is changing the intercept of our regression line by including a categorical variable</p></li>
</ul>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a aria-hidden="true" tabindex="-1"></a>bikes <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">season_pred =</span> <span class="fu">predict</span>(season_lm)) <span class="sc">|&gt;</span> </span>
<span id="cb34-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> rides, <span class="at">y =</span> season_pred)) <span class="sc">+</span></span>
<span id="cb34-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb34-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> season, <span class="at">ncol =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb34-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Actual number of rides"</span>, </span>
<span id="cb34-7"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted number of rides"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-19-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="interactions" class="slide level2">
<h2>Interactions</h2>
<ul>
<li>An interaction allows one predictor’s association with the outcome to depend on values of another predictor</li>
</ul>
<div class="fragment">
<ul>
<li><p>Example: interaction between a categorical variable (<code>season</code>) and a quantitative variable (<code>temp_feel</code>)</p>
<ul>
<li><p>When to include interaction? When we believe relationships between a quantitative variable and the response differ across categories (of a categorical variable)</p></li>
<li><p>4 different lines for each <code>season</code> in modeling relationship between <code>rides</code> and <code>temp_feel</code></p></li>
<li><p>This means those regression lines have different intercepts as well as different slopes</p></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>For more on interactions, see these <a href="https://www.medicine.mcgill.ca/epidemiology/joseph/courses/EPIB-621/interaction.pdf">notes</a></li>
</ul>
</div>
</section>
<section id="visualizing-interactions" class="slide level2">
<h2>Visualizing interactions</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a aria-hidden="true" tabindex="-1"></a>bikes <span class="sc">|&gt;</span> </span>
<span id="cb35-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> temp_feel, <span class="at">y =</span> rides, <span class="at">color =</span> season)) <span class="sc">+</span></span>
<span id="cb35-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a aria-hidden="true" tabindex="-1"></a>  ggthemes<span class="sc">::</span><span class="fu">scale_color_colorblind</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="11-linear_files/figure-revealjs/unnamed-chunk-20-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="interpreting-interactions" class="slide level2">
<h2>Interpreting interactions</h2>
<p><span class="math display">\[
\begin{aligned}
{\text{Rides}} &amp;= \beta_0 + \beta_1 \ \text{Temp} + \beta_2 \ I_{\texttt{spring}} + \beta_3 \ I_{\texttt{summer}} + \beta_4 \ I_{\texttt{winter}} \\
&amp;+ \beta_5 \{ \text{Temp } \times I_{\texttt{spring}} \} +  \beta_6 \{ \text{Temp } \times I_{\texttt{summer}} \} +  \beta_7 \{ \text{Temp } \times I_{\texttt{winter}} \} + \epsilon \\
\end{aligned}
\]</span></p>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a aria-hidden="true" tabindex="-1"></a>interaction_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(rides <span class="sc">~</span> temp_feel <span class="sc">*</span> season, </span>
<span id="cb36-2"><a aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> bikes)</span>
<span id="cb36-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(interaction_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre style="font-size: 0.55em;"><code># A tibble: 8 × 5
  term                   estimate std.error statistic     p.value
  &lt;chr&gt;                     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
1 (Intercept)               238.      773.      0.308 0.758      
2 temp_feel                  54.9      11.0     4.97  0.000000935
3 seasonspring            -3244.     1222.     -2.65  0.00819    
4 seasonsummer             3393.     2921.      1.16  0.246      
5 seasonwinter            -3020.     1032.     -2.93  0.00358    
6 temp_feel:seasonspring     34.4      16.6     2.07  0.0386     
7 temp_feel:seasonsummer    -43.2      35.9    -1.20  0.229      
8 temp_feel:seasonwinter     31.6      15.8     1.99  0.0466     </code></pre>
</div>
</div>
</div><div class="column" style="text-align: left;">
<ul>
<li><p><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> give the slope and intercept for the regression line (describing the relationship between ridership &amp; temperature) for fall season (the reference level)</p></li>
<li><p><span class="math inline">\(\beta_2\)</span> measures the difference in the intercepts between spring and fall seasons</p></li>
<li><p><span class="math inline">\(\beta_5\)</span> shows how much the slopes change as we move from the regression line for fall (the reference level) to the line for spring</p></li>
<li><p>and so on…</p></li>
</ul>
</div></div>
</section>
<section id="multiple-linear-regression" class="slide level2">
<h2>Multiple linear regression</h2>
<p>We can include as many variables as we want (assuming <span class="math inline">\(n &gt; p\)</span>)</p>
<p><span class="math display">\[Y=\beta_{0}+\beta_{1} X_{1}+\beta_{2} X_{2}+\cdots+\beta_{p} X_{p}+\epsilon\]</span></p>
<p>OLS estimates in matrix notation ( <span class="math inline">\(\boldsymbol{X}\)</span> is a <span class="math inline">\(n \times p\)</span> matrix):</p>
<p><span class="math display">\[\hat{\boldsymbol{\beta}} = (\boldsymbol{X} ^T \boldsymbol{X})^{-1}\boldsymbol{X}^T\boldsymbol{Y}\]</span></p>
<div class="fragment">
<p>Can just add more variables to the formula in <code>R</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a aria-hidden="true" tabindex="-1"></a>multiple_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(rides <span class="sc">~</span> temp_feel <span class="sc">+</span> humidity, <span class="at">data =</span> bikes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>Use adjusted <span class="math inline">\(R^2\)</span> when including multiple variables <span class="math inline">\(\displaystyle 1 - \frac{(1 - R^2)(n - 1)}{(n - p - 1)}\)</span></p>
<ul>
<li><p>Adjusts for the number of variables in the model <span class="math inline">\(p\)</span></p></li>
<li><p>Adding more variables <strong>will always increase</strong> the model’s (unadjusted) <span class="math inline">\(R^2\)</span></p></li>
</ul></li>
</ul>
<p>READ THIS: <a href="https://www.stat.cmu.edu/~cshalizi/TALR/TALR.pdf#page=181"><span class="math inline">\(R^2\)</span> myths</a></p>
<p><a href="https://www.tiktok.com/@fatgreggy/video/7186499956058950958">Get your <span class="math inline">\(R^2\)</span> out of here</a></p>
</div>
</section>
<section id="what-about-the-normality-assumption" class="slide level2">
<h2>What about the normality assumption?</h2>
<ul>
<li><p>Model: <span class="math inline">\(Y=\beta_{0}+\beta_{1} X_{1}+\beta_{2} X_{2}+\cdots+\beta_{p} X_{p}+\epsilon\)</span></p></li>
<li><p><span class="math inline">\(\epsilon_i\)</span> is the <strong>random</strong> noise: assume <strong>independent and identically distributed</strong> (<em>iid</em>) from a Normal distribution <span class="math inline">\(\epsilon_i \overset{iid}{\sim}N(0, \sigma^2)\)</span> with constant variance <span class="math inline">\(\sigma^2\)</span></p></li>
</ul>
<div class="fragment">
<ul>
<li><strong>OLS doesn’t care about this assumption</strong>, it’s just estimating coefficients!</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>In order to perform inference, <strong>we need to impose additional assumptions</strong></p></li>
<li><p>By assuming <span class="math inline">\(\epsilon_i \overset{iid}{\sim}N(0, \sigma^2)\)</span>, what we really mean is <span class="math inline">\(Y \overset{iid}{\sim}N(\beta_{0}+\beta_{1} X_{1}+\beta_{2} X_{2}+\cdots+\beta_{p} X_{p}, \sigma^2)\)</span></p></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>So we’re estimating the mean <span class="math inline">\(\mu\)</span> of this conditional distribution, but what about <span class="math inline">\(\sigma^2\)</span>?</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p><a href="https://bradleyboehmke.github.io/HOML/linear-regression.html#simple-linear-regression">Unbiased estimate</a> <span class="math inline">\(\displaystyle \hat{\sigma}^2 = \frac{\text{RSS}}{n - (p + 1)}\)</span></p></li>
<li><p><strong>Degrees of freedom</strong>: <span class="math inline">\(n - (p + 1)\)</span>, data supplies us with <span class="math inline">\(n\)</span> “degrees of freedom” and we used up <span class="math inline">\(p + 1\)</span></p></li>
</ul>
</div>
</section>
<section id="regression-confidence-intervals-vs-prediction-intervals" class="slide level2">
<h2>Regression confidence intervals vs prediction intervals</h2>
<p>Do we want to predict the mean response for a particular value <span class="math inline">\(x^*\)</span> of the explanatory variable or do we want to predict the response for an individual case?</p>
<p>Example:</p>
<ul>
<li><p>if we would like to know the average ridership for <strong>all</strong> days with feels-like temperature of 70 degrees Fahrenheit, then we would use an interval for the <strong>mean response</strong></p></li>
<li><p>if we want an interval to contain the ridership of <strong>a particular</strong> day with feels-like temperature of 70 degrees Fahrenheit, then we need the interval for <strong>a single prediction</strong></p></li>
</ul>
</section>
<section id="regression-confidence-intervals" class="slide level2">
<h2>Regression confidence intervals</h2>
<div class="columns">
<div class="column" style="text-align: left;">
<ul>
<li><code>geom_smooth()</code> displays <strong>confidence intervals</strong> for the regression line</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># predict(simple_lm, interval = "confidence")</span></span>
<span id="cb39-2"><a aria-hidden="true" tabindex="-1"></a>lm_plot <span class="ot">&lt;-</span> bikes <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> temp_feel, <span class="at">y =</span> rides)) <span class="sc">+</span></span>
<span id="cb39-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb39-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span>
<span id="cb39-6"><a aria-hidden="true" tabindex="-1"></a>lm_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-23-1.png" class="quarto-figure quarto-figure-center" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="regression-confidence-intervals-1" class="slide level2">
<h2>Regression confidence intervals</h2>
<ul>
<li><p>Interval estimate for the MEAN response at a given observation (i.e.&nbsp;for the predicted AVERAGE <span class="math inline">\(\hat{\beta}_0 + \hat{\beta}_1 x^*\)</span>)</p></li>
<li><p>Based on standard errors for the estimated regression line at <span class="math inline">\(x^*\)</span> <span class="math display">\[SE_{\text{line}}\left(x^{*}\right)=\hat{\sigma} \cdot \sqrt{\frac{1}{n}+\frac{\left(x^{*}-\bar{x}\right)^{2}}{\sum_{i=1}^{n}\left(x_{i}-\bar{x}\right)^{2}}}\]</span></p></li>
<li><p>Variation only comes from uncertainty in the parameter</p></li>
</ul>
</section>
<section id="regression-prediction-intervals" class="slide level2">
<h2>Regression prediction intervals</h2>
<ul>
<li><p>interval estimate for an INDIVIDUAL response at a given (new) observation</p></li>
<li><p>add the variance <span class="math inline">\(\sigma^2\)</span> of a <strong>single predicted value</strong> <span class="math display">\[SE_{\text{pred}}\left(x^{*}\right)=\hat{\sigma} \cdot \sqrt{1 + \frac{1}{n}+\frac{\left(x^{*}-\bar{x}\right)^{2}}{\sum_{i=1}^{n}\left(x_{i}-\bar{x}\right)^{2}}}\]</span></p></li>
<li><p>Variation comes from uncertainty in parameter estimates and error variance</p></li>
</ul>
</section>
<section id="confidence-intervals-versus-prediction-intervals" class="slide level2">
<h2>Confidence intervals versus prediction intervals</h2>
<p>Generate 95% intervals</p>
<div class="columns">
<div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># predict(simple_lm, interval = "prediction")</span></span>
<span id="cb40-2"><a aria-hidden="true" tabindex="-1"></a>lm_plot <span class="sc">+</span></span>
<span id="cb40-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(</span>
<span id="cb40-4"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> <span class="fu">augment</span>(simple_lm, <span class="at">interval =</span> <span class="st">"prediction"</span>),</span>
<span id="cb40-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">ymin =</span> .lower, <span class="at">ymax =</span> .upper),</span>
<span id="cb40-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">fill =</span> <span class="cn">NA</span></span>
<span id="cb40-7"><a aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>The standard error for predicting an individual response will always be larger than for predicting a mean response</p></li>
<li><p>Prediction intervals will always be wider than confidence intervals</p></li>
</ul>
</div><div class="column" style="text-align: left;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="11-linear_files/figure-revealjs/unnamed-chunk-24-1.png" class="quarto-figure quarto-figure-center" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://36-sure.github.io/2025">36-SURE.github.io/2025</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/36-SURE\.github\.io\/2025\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>