{
  "hash": "e081372761130851c34b2bf4c2c086fe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Supervised learning: generalized linear models\"\nauthor: \"<br>SURE 2025<br><br>Department of Statistics & Data Science<br>Carnegie Mellon University\"\nfooter:  \"[36-SURE.github.io/2025](https://36-sure.github.io/2025)\"\nformat:\n  revealjs:\n    theme: theme.scss\n    chalkboard: true\n    smaller: true\n    slide-number: c/t\n    code-line-numbers: false\n    linestretch: 1.25\n    html-math-method:\n      method: mathjax\n      url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n\n\n\n\n# Background\n\n## Recap\n\n* When the response is continuous, we can use linear regression \n\n* When the response is binary categorical, we can use logistic regression\n\n* Which model do we use if the response contains discrete counts?\n\n## Generalized linear models (GLMs)\n\nThree components of a GLM\n\n. . .\n\n**1. Random component (distribution of the response)**\n\n*   Identifies the response variable and assumes a probability distribution for it\n\n. . .\n\n**2. Linear predictor**\n\n*   Specifies the predictor variables\n  \n*   Linear combination of predictors on the right-hand side of the model equation\n  \n*   In the form $\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$\n\n. . .\n\n**3. Link function (a function of the parameter)**\n\n*   Connects the random component with the linear predictor\n\n*   Via a function of the expected value of the probability distribution of the response\n\nSee also: [Exponential family](https://en.wikipedia.org/wiki/Exponential_family)\n\n## Linear regression\n\n1. $Y \\sim N(\\mu, \\sigma ^2)$\n\n2. Linear predictor: $\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$\n\n3. Identity link function: $g(\\mu) = \\mu$\n\n## Logistic regression\n\n1. $Y \\sim \\text{Binomial}(n,p)$\n\n2. Linear predictor: $\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$\n\n3. Logit link function: $\\displaystyle g(p) = \\log\\left(\\frac{p}{1-p}\\right)$\n\n(Recall: We cannot just simply model $p = \\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$ since the binary response can only take on values of either 0 or 1)\n\n## Poisson regression\n\n1. $Y \\sim \\text{Poisson}(\\lambda)$\n\n2. Linear predictor: $\\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$\n\n3. Log link function: $\\displaystyle g(\\lambda) = \\log (\\lambda)$\n\n(We cannot just simply model $\\lambda = \\beta_0 + \\beta_1 X_1 + \\dots + \\beta_p X_p$ since the counts can only take on non-negative integers)\n\n## Generalization example\n\nIn linear regression, the distribution is normal and the domain of $Y \\mid x$ is $(-\\infty,\\infty)$\n\n. . .\n\nWhat, however, happens if we know that\n\n* the domain of observed values of the response is actually $[0,\\infty]$\n\n* the observed values are __discrete__, with possible values $0, 1, 2, \\dots$\n\n\n. . .\n\n__The normal distribution doesn't hold here__\n\n- Which distribution could possibly govern $Y \\mid x$?\n\n- Remember, we might not know truly how $Y \\mid x$ is distributed, but any assumption we make has to fit with the nature of the data\n\n## Generalization: Poisson regression\n\n-   PMF of a Poisson distribution: $\\displaystyle f(x \\mid \\lambda)= \\frac{ e^{-\\lambda} \\lambda^x}{x!}$; $x = 0, 1, 2, \\dots$ and $\\lambda > 0$\n\n. . .\n\n- Model for the counts of an event in a fixed period of time or space, with a rate of occurrence (intensity) parameter $\\lambda$\n\n. . .\n\n- $\\lambda$ is __both__ the mean and the variance of the distribution\n\n  - in general, the variance governs the distribution's shape\n\n. . .\n\n- distribution of independent event occurences in an interval, e.g. soccer goals in a match\n\n- $\\lambda$ is the average number of the events in an interval\n\n. . .\n\nSo, when we apply GLM in this context, we would identify the family as Poisson\n\nBut there's another step in generalization...\n\n## Generalization: link function\n\nStart with one predictor, linear function: $\\beta_0 + \\beta_1 x$\n\n. . .\n\nRange of this function: $(-\\infty,\\infty)$\n\nBut for Poisson regression, $Y$ __cannot be negative__,\n\n- __We need to transform the linear function__ to be $[0,\\infty)$ \n\n  -   (What if we use linear regression? Results may not be meaningful, e.g., we predict ${\\hat Y}$ to be negative!)\n\n. . .\n\n__There is usually no unique transformation__, but rather conventional ones\n\n## Generalization: link function\n\nFor Poisson, we use the $\\log()$ function as the __link function__ $g()$:\n\n$$g(\\lambda \\mid x) = \\log(\\lambda \\mid x) = \\beta_0 + \\beta_1 x$$\n\n\n(Hence we also call this a [log-linear model](https://en.wikipedia.org/wiki/Log-linear_model))\n\n. . .\n\nGiven $Y$ with values limited to being either 0 or positive integers, with no upper bound, we\n\n1. assume $Y \\mid x \\sim \\text{Poisson}(\\lambda)$\n\n2. assume $\\lambda \\mid x = e^{\\beta_0 + \\beta_1 x}$ \n\n3. use optimization to estimate $\\beta_0$ and $\\beta_1$ by maximizing the likelihood function\n\n\n## More distributions\n\n[Gamma distribution](https://en.wikipedia.org/wiki/Gamma_distribution) (application: modeling TODO INSERT THIS)\n\n+ $Y \\mid x$ continuous, but bounded between 0 and $\\infty$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Gamma_distribution_pdf.svg/650px-Gamma_distribution_pdf.svg.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n## More distributions\n\n[Beta distribution](https://en.wikipedia.org/wiki/Beta_distribution)  (application: modeling TODO INSERT THIS)\n\n+ $Y \\mid x$ continuous, but bounded between 0 and 1\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Beta_distribution_pdf.svg/650px-Beta_distribution_pdf.svg.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n## Modeling count data\n\nGoals scored across men’s soccer matches in the five biggest European leagues during the 2023-2024 season, via the [worldfootballR](https://jaseziv.github.io/worldfootballR) package\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ntheme_set(theme_light())\ngoals <- read_csv(\"https://raw.githubusercontent.com/36-SURE/2025/main/data/goals.csv\")\nglimpse(goals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,504\nColumns: 7\n$ n_goals  <dbl> 1, 0, 1, 0, 1, 2, 1, 2, 0, 1, 1, 2, 1, 3, 1, 2, 2, 4, 1, 2, 0…\n$ xG       <dbl> 2.4, 0.5, 0.3, 0.5, 1.3, 1.2, 2.3, 1.6, 1.0, 1.0, 0.5, 1.6, 0…\n$ off_team <chr> \"Manchester Utd\", \"Ipswich Town\", \"Newcastle Utd\", \"Everton\",…\n$ def_team <chr> \"Fulham\", \"Liverpool\", \"Southampton\", \"Brighton\", \"Bournemout…\n$ league   <chr> \"ENG\", \"ENG\", \"ENG\", \"ENG\", \"ENG\", \"ENG\", \"ENG\", \"ENG\", \"ENG\"…\n$ match_id <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ is_home  <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## EDA: Distribution for the number of goals\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngoals |> \n  count(n_goals) |> \n  ggplot(aes(n_goals, n)) +\n  geom_col(width = 0.5) +\n  scale_x_continuous(breaks = 0:8)\n```\n\n::: {.cell-output-display}\n![](16-glm_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## EDA: Distribution for the number of goals by league\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngoals |> \n  count(n_goals, league) |> \n  ggplot(aes(n_goals, n)) +\n  geom_col(width = 0.5) +\n  scale_x_continuous(breaks = 0:8) +\n  facet_wrap(~ league, nrow = 1)\n```\n\n::: {.cell-output-display}\n![](16-glm_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=1728}\n:::\n:::\n\n\n\n## EDA: Distribution for the number of goals by home/away team\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngoals |> \n  count(n_goals, is_home) |> \n  mutate(is_home = factor(is_home)) |> \n  ggplot(aes(n_goals, n, fill = is_home, group = is_home)) +\n  geom_col(position = \"dodge\", width = 0.5) +\n  scale_x_continuous(breaks = 0:8)\n```\n\n::: {.cell-output-display}\n![](16-glm_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=1440}\n:::\n:::\n\n\n\n## Fitting a poisson regression model\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngoals_poisson <- glm(n_goals ~ league + is_home, family = \"poisson\", data = goals)\n# summary(goals_poisson)\nlibrary(broom)\ntidy(goals_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   0.321     0.0335     9.56  1.19e-21\n2 leagueESP    -0.114     0.0436    -2.61  9.03e- 3\n3 leagueFRA     0.0145    0.0447     0.325 7.45e- 1\n4 leagueGER     0.0659    0.0440     1.50  1.35e- 1\n5 leagueITA    -0.136     0.0439    -3.11  1.90e- 3\n6 is_home       0.122     0.0285     4.27  1.92e- 5\n```\n\n\n:::\n:::\n\n\n\nWhat observations in the dataset correspond to predictions using only the intercept?\n\n## Fitting a poisson regression model\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(goals_poisson, exponentiate = TRUE, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)    1.38     0.0335     9.56  1.19e-21    1.29      1.47 \n2 leagueESP      0.892    0.0436    -2.61  9.03e- 3    0.819     0.972\n3 leagueFRA      1.01     0.0447     0.325 7.45e- 1    0.929     1.11 \n4 leagueGER      1.07     0.0440     1.50  1.35e- 1    0.980     1.16 \n5 leagueITA      0.873    0.0439    -3.11  1.90e- 3    0.801     0.951\n6 is_home        1.13     0.0285     4.27  1.92e- 5    1.07      1.19 \n```\n\n\n:::\n:::\n\n\n\n. . .\n\nWe have sufficient evidence to suggest the expected number of goals is different between ENG teams and each of ESP and ITA, but not FRA or GER, after accounting for home field advantage\n\nThe expected number of goals changes (is multiplied) by a factor of 1.13 (95% CI [1.07, 1.19]) if the team is home in comparison to away teams, after accounting for league\n\n## Model residuals and goodness-of-fit measures \n\n*   Pearson residuals: $\\displaystyle r_i = \\frac{y_i-\\hat{\\lambda}_i}{\\sqrt{\\hat{\\lambda}_i}}$\n\n\n*   Deviance residuals: $\\displaystyle d_i = \\textrm{sign}(y_i-\\hat{\\lambda}_i) \\sqrt{2 \\left[y_i \\log\\left(\\frac{y_i}{\\hat{\\lambda}_i}\\right) -(y_i - \\hat{\\lambda}_i) \\right]}$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresiduals(goals_poisson, type = \"pearson\")\nresiduals(goals_poisson, type = \"deviance\")\n```\n:::\n\n\n\n*   Model summaries\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(goals_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 8\n  null.deviance df.null logLik    AIC    BIC deviance df.residual  nobs\n          <dbl>   <int>  <dbl>  <dbl>  <dbl>    <dbl>       <int> <int>\n1         4269.    3503 -5319. 10650. 10687.    4221.        3498  3504\n```\n\n\n:::\n:::\n\n\n\n**As before, we prefer assessment in terms of out-of-sample/test set performances over these measures**\n\n## Overdispersion\n\n* Overdispersion is a common problem faced in Poisson regression when the variance is larger than what is assumed under the model\n\n. . .\n\n* Recall that a Poisson distribution assumes equidispersion (i.e. the mean and variance are equal)\n\n. . .\n\n* Any concerns here?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvar(goals$n_goals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.519783\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(goals$n_goals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.413527\n```\n\n\n:::\n:::\n\n\n\n## Negative binomial regression\n\nKey idea: introduces another parameter such that the variance can exceed the mean\n\n. . .\n\nWe have $E(Y)  = \\lambda$ and $\\text{Var}(Y)=\\lambda(1+\\alpha \\lambda)$\n\n. . .\n\n* The variance is still proportional to $\\lambda$, but depends on the dispersion parameter $\\alpha \\ge 0$\n\n. . .\n\n* The further $\\alpha$ falls above 0, the greater the overdispersion relative to Poisson variability\n\n. . .\n\n* As $\\alpha$ decreases toward 0, the variance decreases toward $\\lambda$ , and the model converges to a Poisson distribution\n\n. . .\n\nSee [here](https://bookdown.org/roback/bookdown-BeyondMLR/ch-poissonreg.html#negative-binomial-modeling) for more information\n\n## Negative binomial regression\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngoals_nb <- MASS::glm.nb(n_goals ~ league + is_home, data = goals)\nsummary(goals_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nMASS::glm.nb(formula = n_goals ~ league + is_home, data = goals, \n    init.theta = 23.79903563, link = log)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.32064    0.03453   9.286  < 2e-16 ***\nleagueESP   -0.11413    0.04487  -2.544  0.01097 *  \nleagueFRA    0.01435    0.04603   0.312  0.75530    \nleagueGER    0.06584    0.04543   1.449  0.14726    \nleagueITA   -0.13628    0.04512  -3.021  0.00252 ** \nis_home      0.12180    0.02931   4.156 3.24e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(23.799) family taken to be 1)\n\n    Null deviance: 4060.9  on 3503  degrees of freedom\nResidual deviance: 4015.6  on 3498  degrees of freedom\nAIC: 10646\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  23.8 \n          Std. Err.:  10.2 \n\n 2 x log-likelihood:  -10631.63 \n```\n\n\n:::\n:::\n\n\n\n## Zero-inflated Poisson regression\n\n*   One common problem in modeling count data is the prevalence of zeros\n\n. . .\n\n*   While the Poisson distribution allows for zero counts, there are problems with a lot more zeros observed than expected for Poisson data\n\n. . .\n\n*   A **zero-inflated Poisson (ZIP) model** is a mixture model with two components\n\n    *   Logistic regression model to predict whether the response will be zero (whether 0 goals are observed) $$P(Y = 0) = \\pi + (1 - \\pi)e^{\\lambda}$$\n\n    *   Poisson regression model for non-zero counts (non-zero goal values) $$P(Y = y) = (1 - \\pi) \\frac{\\lambda^y e^{-\\lambda}}{y!}, \\text{\nfor } y = 1, 2, 3, \\dots$$\n    \n\n## Zero-inflated Poisson (ZIP) regression\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(pscl) # install.packages(\"pscl\")\ngoals_zip <- zeroinfl(n_goals ~ league + is_home, data = goals)\nsummary(goals_zip)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nzeroinfl(formula = n_goals ~ league + is_home, data = goals)\n\nPearson residuals:\n    Min      1Q  Median      3Q     Max \n-1.2381 -1.0887 -0.3100  0.5239  5.0085 \n\nCount model coefficients (poisson with log link):\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.336872   0.039204   8.593  < 2e-16 ***\nleagueESP   -0.141382   0.049638  -2.848  0.00440 ** \nleagueFRA    0.002821   0.057836   0.049  0.96110    \nleagueGER    0.124432   0.059075   2.106  0.03517 *  \nleagueITA   -0.152638   0.055749  -2.738  0.00618 ** \nis_home      0.142767   0.034039   4.194 2.74e-05 ***\n\nZero-inflation model coefficients (binomial with logit link):\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -4.1160     0.9155  -4.496 6.92e-06 ***\nleagueESP    -8.4725    48.4009  -0.175    0.861    \nleagueFRA    -0.5554     2.0040  -0.277    0.782    \nleagueGER     1.1872     1.0255   1.158    0.247    \nleagueITA    -0.9125     2.5750  -0.354    0.723    \nis_home       0.8414     0.8559   0.983    0.326    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n\nNumber of iterations in BFGS optimization: 52 \nLog-likelihood: -5312 on 12 Df\n```\n\n\n:::\n:::\n\n\n\n## Model comparison: Poisson vs ZIP\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(2008)\nn_folds <- 5\ngoals_folds <- goals |> \n  distinct(match_id) |>\n  mutate(match_fold = sample(rep(1:n_folds, length.out = n())))\n\n# goals_folds |> count(match_fold)\n\ngoals <- goals |> \n  left_join(goals_folds, by = \"match_id\")\n```\n:::\n\n\n\n## Cross-validation\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoisson_cv <- function(k) {\n\n  train_goals <- goals |> \n    filter(match_fold != k)\n  test_goals <- goals |> \n    filter(match_fold == k)\n\n  poisson_fit <- glm(n_goals ~ league + is_home, family = \"poisson\", data = train_goals)\n  poisson_test_preds <- predict(poisson_fit, newdata = test_goals, type = \"response\")\n  \n  # return a table with RMSE and fold id\n  poisson_out <- tibble(rmse = sqrt(mean((test_goals$n_goals - poisson_test_preds) ^ 2)), \n                        match_fold = k)\n  return(poisson_out)\n}\n\npoisson_cv_results <- map(1:n_folds, poisson_cv) |> \n  list_rbind()\n```\n:::\n\n\n\n## Cross-validation\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nzip_cv <- function(k) {\n\n  train_goals <- goals |> \n    filter(match_fold != k)\n  test_goals <- goals |> \n    filter(match_fold == k)\n  \n  zip_fit <- zeroinfl(n_goals ~ league + is_home, data = train_goals)\n  zip_test_preds <- predict(zip_fit, newdata = test_goals)\n  \n  zip_out <- tibble(rmse = sqrt(mean((test_goals$n_goals - zip_test_preds)^2)),\n                    match_fold = k)\n  return(zip_out)\n}\n\nzip_cv_results <- map(1:n_folds, zip_cv) |> \n  list_rbind()\n```\n:::\n\n\n\n## Out-of-sample comparison\n\nWhich model would you select?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoisson_cv_results |> \n  summarize(avg_rmse = mean(rmse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  avg_rmse\n     <dbl>\n1     1.23\n```\n\n\n:::\n\n```{.r .cell-code}\nzip_cv_results |> \n  summarize(avg_rmse = mean(rmse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  avg_rmse\n     <dbl>\n1     1.23\n```\n\n\n:::\n:::\n\n\n\n. . .\n\nRemember: [Occam's razor](https://en.wikipedia.org/wiki/Occam%27s_razor)\n\n## Resources\n\n*   [Bivariate Poisson regression](https://doi.org/10.1111/1467-9884.00366)\n\n*   [Generalized Poisson regression](https://doi.org/10.1080/03610929208830766)\n\n*   [Skellam regression](https://arxiv.org/pdf/1807.07536)\n\n*   [Conway-Maxwell-Poisson regression](https://doi.org/10.1007/s11222-023-10244-0)\n\n*   Poisson–Tweedie regression\n\n## Appendix: Code to build dataset\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(worldfootballR)\nlibrary(tidyverse)\nbig5 <- fb_match_results(country = c(\"ENG\", \"ESP\", \"ITA\", \"GER\", \"FRA\"),\n                         gender = \"M\", \n                         season_end_year = 2025, \n                         tier = \"1st\")\nbig5 <- big5 |>\n  mutate(match_id = row_number()) |>  # add unique id for each row\n  filter(!is.na(Wk))\n  \nhome_goals <- big5 |>\n  select(n_goals = HomeGoals, xG = Home_xG, off_team = Home, def_team = Away, league = Country, match_id) |>\n  mutate(is_home = 1)\n\naway_goals <- big5 |>\n  select(n_goals = AwayGoals, xG = Away_xG, off_team = Away, def_team = Home, league = Country, match_id) |>\n  mutate(is_home = 0)\n\ngoals <- home_goals |>\n  bind_rows(away_goals)\n  \n# write_csv(goals, \"goals.csv\")  \n```\n:::",
    "supporting": [
      "16-glm_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}